### ISSUE TITLE
TMC identity for the 1.37M space

### ISSUE THREAD

**Issue by chenruduan** [hkneiding/PL-MOGA#2]
Hi,

I am interested in the 1.37M chemical space of transition metal complexes (TMCs). I see the `ground_truth_fitness_values.csv` that contains the id of TMC and its corresponding two properties. I am wondering how we can map the id to the real TMC (say, Pd(L1)(L2)(L3)(L4))? Thanks!

Best,
Chenru

**Comment by hkneiding** [comment]
I added the ligand names as a separate column to the CSV (now compressed as zip due to size constraints on GitHub). You can find the structures corresponding to the ligand names for the 1.37M space [here](https://github.com/hkneiding/PL-MOGA/blob/main/ligands/ligands-1M.xyz).
