### ISSUE TITLE
Is the order of ligand attachments to the Pd shuffled in molsimplify?

### ISSUE THREAD

**Issue by HelloJocelynLu** [hkneiding/PL-MOGA#3]
Hi,

Thank you for the nice work! I am working on the 1.37M chemical space of transition metal complexes (TMCs) data table with calculated polarisability and homo-lumo gap values. I really appreciate that ligand names are added as a separate column. I see that you are using molsimplify to generate complex structures. However, I noticed that when molsimplify was called, it does not come with `-ligalign` or `-ligloc` option.
Source code:
https://github.com/hkneiding/PL-MOGA/blob/614d8bec32181859b86936814dd6848996c9e82e/benchmarks/benchmark_1M/main.py#L272-L280

I checked the molsimplify manual, and find that:
```
... 
-ligalign True tells molSimplify to use a smart alignment algorithm. This means,
that the order that the ligands will be attached to the metal will be shuffled according to
their denticities and size so that the best possible structure is obtained (default is True).
...
By default, molSimplify will attach ligands to the best possible
positions on the coordination template and not necessary in the order specified by the user.
If the user wants to attach ligands to specific points in space, the force location option needs
to be enabled. 
...
```

It seems that this `-ligalign` is True and `-ligloc` is False by default
<img width="574" alt="image" src="https://github.com/user-attachments/assets/5b809994-b82c-4c71-ae04-5422ff273e2a">
Which means that the complexes generated by molsimplify (and the corresponding calculated values) may not have consistent order specified in the ligands column?

**Comment by hkneiding** [comment]
Thank you for your interest in our project!

We tested the use of the ligalign flag and found that the default actually seems to be False. You can try this yourself by running 
`molsimplify -skipANN True -core Pd -geometry sqp -coord 4 -ligocc 1,1,1,1 -oxstate 2 -lig water,ammonia,water,ammonia`
and 
`molsimplify -skipANN True -ligalign True -core Pd -geometry sqp -coord 4 -ligocc 1,1,1,1 -oxstate 2 -lig water,ammonia,water,ammonia`
and comparing the resulting xyzs.

In our testing they were different, while the first command does not change the ordering (ligands stay in an alternating pattern), the second command actually does lead to a reordering of ligands (water and ammonia ligands are now placed next to each other). Therefore we concluded that -ligalign is False by default.

I hope this helps. Please let me know if you have trouble reproducing this.

**Comment by HelloJocelynLu** [comment]
> Thank you for your interest in our project!
> 
> We tested the use of the ligalign flag and found that the default actually seems to be False. You can try this yourself by running `molsimplify -skipANN True -core Pd -geometry sqp -coord 4 -ligocc 1,1,1,1 -oxstate 2 -lig water,ammonia,water,ammonia` and `molsimplify -skipANN True -ligalign True -core Pd -geometry sqp -coord 4 -ligocc 1,1,1,1 -oxstate 2 -lig water,ammonia,water,ammonia` and comparing the resulting xyzs.
> 
> In our testing they were different, while the first command does not change the ordering (ligands stay in an alternating pattern), the second command actually does lead to a reordering of ligands (water and ammonia ligands are now placed next to each other). Therefore we concluded that -ligalign is False by default.
> 
> I hope this helps. Please let me know if you have trouble reproducing this.

Thank you for looking into this!

I referred to an  [outdated manual](https://hjkgrp.mit.edu/tutorials/2016-12-02-molsimplify-tutorial-2-slab-builder/molSimplify_v1.pdf) (Molsimplify v1) and noted that the default setting was changed years ago in this commit:
https://github.com/hjkgrp/molSimplify/commit/361776aeb1ead1a5de5036dce24fb53e7f073e51#diff-a2d96af22e65307335c706dd0cf8c37337aedc721735ece007da83bacae94a42

The default value for -ligalign should now indeed be False. 

Thank you for the clarification!
