### ISSUE TITLE
Access to DFT calculated properties

### ISSUE THREAD

**Issue by HelloJocelynLu** [hkneiding/PL-MOGA#4]
Hi,

I have been following your work and noticed that the (DFT) property distribution of the 60K tmQMg dataset from SI Fig 13 differs from the xtb calculated results (ground_truth_fitness_values.csv).

![img_v3_02f2_00ff22e2-853f-4a15-837a-5ac46260203h](https://github.com/user-attachments/assets/81019124-1924-4b75-8436-fd5021620e12)

Is it possible to access the DFT calculated data?

Thank you!

**Comment by hkneiding** [comment]
Hi,

thank you for you interest in our work! Can you clarify what exactly you are interested in: the DFT properties of the tmQMg dataset or the 1.37M space?

**Comment by HelloJocelynLu** [comment]
> Hi,
> 
> thank you for you interest in our work! Can you clarify what exactly you are interested in: the DFT properties of the tmQMg dataset or the 1.37M space?

Hi,

Thank you for your response. I would prefer DFT properties for the 1.37M space, if available, but the properties of the tmQMg dataset are also helpful!

**Comment by hkneiding** [comment]
Due to computational constraints we have calculated the quantum properties of the 1.37M space only at the xTB level. 

You can find the quantum properties of the tmQMg dataset on the associated [GitHub page](https://github.com/uiocompcat/tmQMg/tree/main/data).

I hope this helps!
